### ISSUE TITLE
Link do Notion

### ISSUE THREAD

**Issue by marconneves** [DanielSLucas/NLW02_Proffy#1]
Amigo, estava eu tentando conseguir o link da versão 2, vocês não teria o link disponivel ai não?

**Comment by DanielSLucas** [comment]
Tenho sim! Acessa ae https://www.notion.so/Vers-o-2-0-Proffy-68b4474745bf4036b834c1aa69408de1

**Comment by marconneves** [comment]
Opa, vlew, estou tentando botar meus projetos em dias heheh
